# The Defaults List is a list in an input config that instructs Hydra how to build the output config.
defaults:
  - dataset: ZINC_1B_smiles_bpe_streaming
  - model: llama-32M
  - finetune: augment_hc_trainer_pmo_32M_SMILES_BPE
  - trainer: hf_trainer_one_epoch
  - _self_

trainer:
  per_device_train_batch_size: 2400
  per_device_eval_batch_size: 2400
  gradient_accumulation_steps: 2

finetune:
  checkpoint: "chandar-lab/NovoMolGen_32M_SMILES_BPE"
  n_jobs: 4

seed: 42
save_path: './save'
wandb_logs: true

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d-%H-%M-%S}/hydra
