# The Defaults List is a list in an input config that instructs Hydra how to build the output config.
defaults:
  - dataset: ZINC_1B_smiles_bpe_streaming
  - model: llama-32M
  - finetune: augment_hc_trainer_pmo_32M_SMILES_BPE
  - trainer: hf_trainer_one_epoch
  - _self_

finetune:
  n_jobs: 4
  prefill_drop_non_roundtrip: false
  prefill_roundtrip_oversample_factor: 1

seed: 42
save_path: './save'
wandb_logs: true

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d-%H-%M-%S}/hydra
